export const ADD_DIGIT = 'ADD_DIGIT'
export const CHOOSE_ACTION = 'CHOOSE_ACTION'
export const CALCULATE = 'CALCULATE'
export const CLEAR_ALL = 'CLEAR_ALL'
export const CLEAR = 'CLEAR'
export const DELETE_DIGIT = 'DELETE_DIGIT'
